name: Check for refleaks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  hunt_refleaks:
    runs-on: ubuntu-latest
    name: Check for refleaks
    steps:
      - uses: actions/checkout@v2
      - uses: deadsnakes/action@v3.2.0
        with:
          python-version: 3.10-dev
          debug: true
      - run: python -m mutable_lattice.test_refleaks